### ISSUE TITLE
Mistake / old information in Readme for command-line arguments

### ISSUE THREAD

**Issue by patrikhuber** [ybayle/Scyland3D#13]
I think I found another piece of information in the Readme that doesn't match the actual command-line parameters (perhaps you forgot to update those when you switched to the new cmdline options module).

Readme says:

> Command line: python -m Scyland3D.Scyland3D -v False for removing the display of information to the console.

Output:

```
python -m Scyland3D.Scyland3D -v False
usage: Scyland3D.py [-h] [-i INDIR] [-o OUTDIR] [-m MIRROR_FACTOR] [-r ORDER]
                    [-f ORDER_FACTOR] [-n FEATURE_NAMES] [-v]
Scyland3D.py: error: unrecognized arguments: False
```

Could you also check all the other examples in the readme please whether they work as expected?

**Comment by ybayle** [comment]
I updated all examples from command line and from python. Could you tell me if everything is ok on your side?

**Comment by patrikhuber** [comment]
A couple more questions:

> This is only valid if the keyword upper is present in the file name.

I'm a bit confused what that exactly means. In the filename? Or within one of the .pts files in the directory given with `-i`? In case of the latter, I am still confused because none of these files contains the string "upper" (or I am not finding it / looking in the wrong place?)

Also when I run the given command, `python -m Scyland3D.Scyland3D -i "path/" -f "upper" -r "36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 37"`, on the `example/` directory, a file `landmarks_reordered.csv` gets written.
If I replace `-f "upper"` by `-f "lower"`, it writes a file `landmarks.csv`. Why this unexpected and (for me) unintuitive difference?

The other commands exhibit the same behaviour, e.g. with `landmarks_reversed.csv` etc.

> Command line: python -m Scyland3D.Scyland3D -i "path/" -m "upper" will mirror in 3D the files containing the keyword upper before processing them with the remaining lower items as depicted in the figure below:

The figure is no longer below that text. Also if you give a non-existent argument like "asdf", there will be no error. Is that expected?
The text description is also not 100% clear to me. "will mirror in 3D the files containing the keyword upper before processing them with the remaining lower items"? "...before processing them with the remaining..."?

**Comment by ybayle** [comment]
`AssertionError: The order_factor (asdf) provided has not been found in any file names.`

**Comment by ybayle** [comment]
> I'm a bit confused what that exactly means. In the filename? Or within one of the .pts files in the directory given with -i? In case of the latter, I am still confused because none of these files contains the string "upper" (or I am not finding it / looking in the wrong place?)

The folder `https://github.com/ybayle/Scyland3D/tree/master/Scyland3D/example/` contains three pts files with the keyword `upper` and two with the keyword `lower`.

> Also when I run the given command, python -m Scyland3D.Scyland3D -i "path/" -f "upper" -r "36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1, 0, 37", on the example/ directory, a file landmarks_reordered.csv gets written.
If I replace -f "upper" by -f "lower", it writes a file landmarks.csv. Why this unexpected and (for me) unintuitive difference?

Thanks for finding this bug in the outputfilename. This is now fixed. 

> Also if you give a non-existent argument like "asdf", there will be no error. Is that expected?

The error message `AssertionError: The order_factor (asdf) provided has not been found in any file names.` was displayed for an invalid order_factor but not for a mirror_factor. This is a bug that is now fixed.

> The text description is also not 100% clear to me. "will mirror in 3D the files containing the keyword upper before processing them with the remaining lower items"? "...before processing them with the remaining..."?

The word `remaining` has been removed for clarity. Indeed all files are processed but a preprocessing is applied to the `upper` ones.

**Comment by patrikhuber** [comment]
> Command line: python -m Scyland3D.Scyland3D -i "path/" -m "upper" will mirror in 3D the files containing the keyword upper before processing them with the lower items as depicted in the figure above.

I am still not sure the second part (after the "before...") is clear. If I understand correctly, what you want to say is "...before processing the remaining files (without mirroring them).". Correct? And the figure depicts the mirroring, so it only applies to the first part of the sentence?

---

If you specify part of a string, e.g. `... -f "u"`, then it runs as well. I guess because it matches the "u" to "upper"? Is this expected, or would it not be better to search for an _exact_ match? Otherwise if a file contains `_lower_` in the filename but contains an `u` somewhere else (maybe you're procesing mo**u**ths and not teeth!), it would match it and reorder as well?

Also I understand now that you're really referring to the filename, and not to the file content. Encoding information in the filename is a tricky business, in my opinion. It might be unavoidable though if you don't have control over the content of the .pts file / format. In that case, you should just document it better that the **filename** of the files actually matter and that they have to have a specific format (e.g. separated by `_` or `-` or something so that exact matches can be produced).

An even better solution might be that you take as input to the script not a whole folder, but only a single file (usually this is better practice anyway), and then the order arguments can be given directly, without having to parse filenames. If someone then needs to process a whole folder, they would write their own script around yours that handles the folder processing and filename convention. (You could also supply this, separately).

Anyway this decision I would leave up to you, just some input to consider from my side.

**Comment by ybayle** [comment]
> I am still not sure the second part (after the "before...") is clear. If I understand correctly, what you want to say is "...before processing the remaining files (without mirroring them).". Correct? And the figure depicts the mirroring, so it only applies to the first part of the sentence?

I have updated the sentence as follow:

```Command line: `python -m Scyland3D.Scyland3D -i "path/" -m "upper"` will mirror in 3D -as depicted in the figure above- the landmarks stored in `.pts` file with the keyword `upper` in their filename. Then, it will export to a `.csv` file those processed landmarks and also the unprocessed landmarks from  `.pts` file that do not contain the keyword `upper` in their filename.```

> If you specify part of a string, e.g. ... -f "u", then it runs as well. I guess because it matches the "u" to "upper"?

Yes, indeed.

> Is this expected, or would it not be better to search for an exact match? Otherwise if a file contains _lower_ in the filename but contains an u somewhere else (maybe you're procesing mouths and not teeth!), it would match it and reorder as well? Also I understand now that you're really referring to the filename, and not to the file content. Encoding information in the filename is a tricky business, in my opinion. It might be unavoidable though if you don't have control over the content of the .pts file / format. In that case, you should just document it better that the filename of the files actually matter and that they have to have a specific format (e.g. separated by _ or - or something so that exact matches can be produced).

You're right, I have added a warning in the ReadMe to document it better. The user should be careful when typing keywords, and I consider this less dangerous than having a typo in a command line like `rm filename.txt`.

> An even better solution might be that you take as input to the script not a whole folder, but only a single file (usually this is better practice anyway), and then the order arguments can be given directly, without having to parse filenames. If someone then needs to process a whole folder, they would write their own script around yours that handles the folder processing and filename convention. (You could also supply this, separately). Anyway this decision I would leave up to you, just some input to consider from my side.

The user can currently process a single file and call the script multiple times for each of his file. Or the user can use the ability to process multiple files.

**Comment by patrikhuber** [comment]
> Command line: `python -m Scyland3D.Scyland3D -i "path/" -m "upper"` will mirror in 3D -as depicted in the figure above- the landmarks stored in `.pts` file with the keyword `upper` in their filename. Then, it will export to a `.csv` file those processed landmarks and also the unprocessed landmarks from `.pts` file that do not contain the keyword `upper` in their filename.

I think this sentence is more clear but a bit convoluted now. I am not a native speaker either but how about this slight modification?

> Command line: `python -m Scyland3D.Scyland3D -i "path/" -m "upper"` will mirror in 3D the landmarks stored in `.pts` files with the keyword `upper` in their filename. Then, it will export to a `.csv` file those mirrored landmarks and also the unprocessed landmarks from `.pts` files that do not contain the keyword `upper` in their filename. The figure above depicts the mirroring.

---

> I consider this less dangerous than having a typo in a command line like rm filename.txt.

Well certainly deleting files by accident can be dangerous, especially if one doesn't have a backup ;-)
But I would argue that these sort of "silent mistakes" like here, are potentially more dangerous, particularly in research environments. You will run a command, often on several files, you will not hand-check all the resulting files usually, and you may never discover that some points that you thought got mirrored actually didn't, or the other way round.

Personally, I think the Scyland3D documentation is still not clear enough to allow someone *not* already familiar with it to understand how all this filename-stuff and the order-factor etc. works, and what the potential gotchas are. If we didn't have this discussion, I don't think I would be able to confidently use it, just from reading the Readme.

Anyway I will leave it at that - I feel like some of that might just be my personal opinion/preference, and I feel like my job as reviewer is done. It might be perfectly clear to other people and I know that A) reviewers aren't always right and B) authors can't (or don't want to) always fully please all reviewers :-).

Thanks for all the explanations and I'm sure they'll be helpful to your other users!

**Comment by ybayle** [comment]
> I think this sentence is more clear but a bit convoluted now. I am not a native speaker either but how about this slight modification?

Thanks for the suggestion that is clearer thanks to the sentences being split up. I have updated accordingly the readme.

> Well certainly deleting files by accident can be dangerous, especially if one doesn't have a backup ;-) But I would argue that these sort of "silent mistakes" like here, are potentially more dangerous, particularly in research environments. You will run a command, often on several files, you will not hand-check all the resulting files usually, and you may never discover that some points that you thought got mirrored actually didn't, or the other way round. Personally, I think the Scyland3D documentation is still not clear enough to allow someone not already familiar with it to understand how all this filename-stuff and the order-factor etc. works, and what the potential gotchas are. If we didn't have this discussion, I don't think I would be able to confidently use it, just from reading the Readme. Anyway I will leave it at that - I feel like some of that might just be my personal opinion/preference, and I feel like my job as reviewer is done. It might be perfectly clear to other people and I know that A) reviewers aren't always right and B) authors can't (or don't want to) always fully please all reviewers :-). Thanks for all the explanations and I'm sure they'll be helpful to your other users!

I'll discuss more with people using Scyland3D to see how we can improve and avoid these kind of silent bug.
Thank you very much for all your advices, suggestions, and the bug you found that helped improve the software and its usability!

**Comment by patrikhuber** [comment]
You're welcome, and all the best! :)
